### ISSUE TITLE
Add system settings to meta information of acquisition data

### ISSUE THREAD

**Issue by schote** [schote/spectrum-console#32]
- [ ] Parameter of `TxCard`: Output level, filter type, sample rate
- [ ] Parameter of `RxCard`:
- [ ] Parameter of `SequenceProvider`: rf to volt scaling, gpa scaling, gradient coefficients, enabled channels, impedance, max. amplitudes
